### ISSUE TITLE
Error: There is no prebuilt TDLib for your platform (darwin arm64).

### ISSUE THREAD

**Issue by munjalmukul** [AlexXanderGrib/node-tdlib#7]
getting error on this line

`
import { Client, Authenticator } from 'tdlib-native';

import { TDLibAddon } from 'tdlib-native/addon';

const adapter = await TDLibAddon.create();
 `

**Comment by AlexXanderGrib** [comment]
Hello, please show the error and node version

**Comment by AlexXanderGrib** [comment]
Fixed in 2.5.0 with tdlib 1.8.33

**Comment by tx-tomcat** [comment]
error still persist. Node v18.19

**Comment by AlexXanderGrib** [comment]
> error still persist. Node v18.19

Try upgrading to latest tdlib-native (2.6.0 at this time)

**Comment by AlexXanderGrib** [comment]
Probably fixed
